### ISSUE TITLE
Create MyBinder template for IPYNB

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns#10]
https://mybinder.org/

**Comment by annamunhoz** [comment]
Hi. I tried it but something went wrong. See error below.

![image](https://user-images.githubusercontent.com/53128839/66710194-f3c9e080-ed49-11e9-82b6-278d46406d35.png)

**Comment by ucalyptus** [comment]
The problem lies in that in the requirements.txt the specific required version of PIL has not been mentioned.
Check the first comment here. 
https://www.reddit.com/r/learnpython/comments/a2osgp/pil_or_pillow/

**Comment by ucalyptus** [comment]
https://mybinder.org/v2/gh/ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns/master

**Comment by annamunhoz** [comment]
Oh, I see. Sorry I couldn't help with this.
