### ISSUE TITLE
Refactoring ipynb

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns#2]
Find the different parts of the code from the notebook and put them under different modules.

**Comment by lkdmttg7** [comment]
Can I work on this?

**Comment by ucalyptus** [comment]
@lkdmttg7 sure

**Comment by ucalyptus** [comment]
@lkdmttg7 Please follow procedures of refactoring as in :
https://github.com/ucalyptus/Detecting-Ships/

**Comment by ucalyptus** [comment]
While making a PR, reference this issue with {hashtag}{issue_number}

**Comment by ucalyptus** [comment]
@lkdmttg7 What is the status?

**Comment by lkdmttg7** [comment]
It will be done by tomorrow. Is it fine?

**Comment by ucalyptus** [comment]
Ok.

**Comment by ucalyptus** [comment]
Open to everyone
