### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by ucalyptus** [ucalyptus/Pneumothorax-Segmentation-using-Hypercolumns#4]
Comment for explanation .

**Comment by alexandriaroberts** [comment]
Hi! What is it you would like to do?

**Comment by lkdmttg7** [comment]
I would like to work on this as well.

**Comment by subhadeep-deyashi** [comment]
What do I need to do?

**Comment by ucalyptus** [comment]
1. reduce image size
2. add https://carbon.now.sh for each module (comes after refactoring issue is resolved)

cc: @subhadeep-deyashi @lkdmttg7

**Comment by ucalyptus** [comment]
@subhadeep-deyashi any updates?

**Comment by annamunhoz** [comment]
Hi. I was going to do issue #10 but something went wrong. So I ended up doing the image resize and reorganized some infos in the readme. I hope it's fine. :)
